config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :videos
  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :url, presence: { message: "cannot be blank" }
  validates :url, format: { with: URI::regexp(['http', 'https']), message: "must be valid" }
  validates :description, presence: { message: "cannot be blank" }
  validates :rating, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0,
    message: "must be between 0 and 5"
  }
end

app/models/video.rb
class Video < ActiveRecord::Base

  validates :url, presence: {message: "URL cannot be blank"}
  validates :url, format: {
    with: URI::regexp(['https', 'http']),
    message: "URL must be valid",

  }

  validates :rating, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0,
    message: "Rating must be between 0 and 5"
  }

  validates :description, presence: {message: "Description cannot be blank"}

  def print_youtube_id
    self.url.split('=').last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(
      url: params[:picture][:url],
      description: params[:picture][:description],
      rating: params[:picture][:rating]
    )
    if @picture.save
      redirect_to picture_path(@picture), notice: "Picture successfully created"
    else
      render new_picture_path
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])

  end

  def update
    @picture = Picture.find(params[:id])
    @picture.url = params[:picture][:url]
    @picture.description = params[:picture][:description]
    @picture.rating = params[:picture][:rating]

    if @picture.save
      redirect_to picture_path(@picture)
    else
      redirect_to edit_picture_path(@picture), notice: "Field cannot be empty"
    end

  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.create(safe_params)

    if @video.save
      redirect_to video_path(@video), notice: "Video successfully created"
    else
      render "new"
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(safe_params)
    if @video.save
      redirect_to video_path(@video), notice: "Video successfully updated"
    else
      render "edit"
    end
  end

  private

  def safe_params
    params.require(:video).permit(:url, :description, :rating)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="fixed_header">
  <div id="header_container">
  <h1>Media Manager</h1>
  <nav class="main_links">
    <a href="/pictures">all pictures</a>
    <a href="/videos">all videos</a>
  </nav>
  </div>
</header>
<main>
  <%= yield %>
</main>

<footer>
  <div id="footer_container">
  <h4>Not copyrighted at all</h4>
  </div>
</footer>
</body>
</html>

app/views/pictures/edit.html.erb
<% if flash[:notice] %>
  <p class="error"><%= flash[:notice] %></p>
<% end %>

<h2 class="form_header">Add Picture</h2>
<%= form_for @picture do |f| %>

  <% @picture.errors.full_messages.each do |error| %>
    <p class="error"> <%= error.gsub("Url", "URL") %></p>
  <% end %>


  <p>
    <%= f.label :url, "URL of Photo", class: "form-label" %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :description, "Short Description", class: "form-label" %>
    <%= f.text_area :description, class: "description" %>
  </p>

  <p>
    <%= f.label :rating, class: "form-label" %>
    <%= f.text_field :rating, class: "rating_field" %>
  </p>

  <p>
    <%= f.submit class: "form-button" %>
  </p>

<% end %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<%= link_to 'New Picture', new_picture_path %>
<section class="pictures">

  <% @pictures.each do |picture| %>
    <div class="frame">
      <a href="<%= "/pictures/#{picture.id}" %>" class="indexed_image"><img src="<%= picture.url %>"></a>
    </div>
  <% end %>

</section>

app/views/pictures/new.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h2 class="form_header">Add Picture</h2>
<%= form_for @picture do |f| %>

  <% @picture.errors.full_messages.each do |error| %>
    <p class="error"> <%= error.gsub("Url", "URL") %></p>
  <% end %>


  <p>
    <%= f.label :url, "URL of Photo", class: "form-label" %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :description, "Short Description", class: "form-label" %>
    <%= f.text_area :description, class: "description" %>
  </p>

  <p>
    <%= f.label :rating, class: "form-label" %>
    <%= f.text_field :rating, class: "rating_field" %>
  </p>

  <p>
    <%= f.submit class: "form-button" %>
  </p>

<% end %>

app/views/pictures/show.html.erb
<div class="flash_notice">
  <p><%= flash[:notice] %></p>
</div>



<div class="show_pic">
  <img width="448" height="252" class="picture_frame" src="<%= @picture.url %>" frameborder="0" allowfullscreen>

  <div class="show_container">
    <a href="<%= @picture.url %>"><%= @picture.url %></a>
    <%= link_to '(Edit)', edit_picture_path(@picture), class: 'edit_button' %>

    <div class="show_description">
      <%= simple_format(@picture.description)%>
    </div>
  </div>

  <div class="show_pic_rating">
    <p>Rating: <%= @picture.rating %> out of 5</p>
  </div>
</div>

app/views/videos/edit.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h2 class="form_header">Edit Video</h2>
<%= form_for @video do |f| %>

  <% @video.errors.messages.each do |error| %>
    <p class="error"><%= error.last.first %></p>
  <% end %>

  <p>
    <%= f.label :url, "URL of Video", class: "form-label" %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :description, "Short Description", class: "form-label" %>
    <%= f.text_area :description, class: "description" %>
  </p>

  <p>
    <%= f.label :rating, class: "form-label" %>
    <%= f.text_field :rating, class: "rating_field" %>
  </p>

  <p>
    <%= f.submit "Edit Video", class: "form-button" %>
  </p>

<% end %>

app/views/videos/index.html.erb
<p class="new_video_link">
  <%= link_to 'New Video', new_video_path %>
</p>
<% @videos.each do |video| %>
  <p>
    <%= link_to "#{video.url}", video_path(video.id) %>
  </p>
<% end %>

app/views/videos/new.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h2 class="form_header">Add Video</h2>
<%= form_for @video do |f| %>

  <% @video.errors.messages.each do |error| %>
 <p class="error"><%= error.last.first %></p>
  <% end %>

  <p>
    <%= f.label :url, "URL of Video", class: "form-label" %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :description, "Short Description", class: "form-label" %>
    <%= f.text_area :description, class: "description" %>
  </p>

  <p>
    <%= f.label :rating, class: "form-label" %>
    <%= f.text_field :rating, class: "rating_field" %>
  </p>

  <p>
    <%= f.submit "Add Video", class: "form-button" %>
  </p>

<% end %>

app/views/videos/show.html.erb
<div class="flash_notice">
  <%= flash[:notice] %>
</div>

<div class="show_video">
  <iframe width="448" height="252" src="//www.youtube.com/embed/<%= @video.print_youtube_id %>" frameborder="0" allowfullscreen></iframe>
</div>

<div class="show_container">
  <a href="<%= @video.url %>"><%= @video.url %></a>

  <div class="show_description">
    <%= simple_format(@video.description) %>
  </div>
</div>

<div class="show_rating">
  <p>Rating: <%= @video.rating %> out of 5</p>
</div>

<%= link_to 'Edit', edit_video_path %>